import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}> 
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/aboutus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AboutUs
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/services" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Services
          </Link>
        </li>
      <li style={{ marginBottom: "10px" }}>
        <Link to="/publication" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Publication
        </Link>
      </li>
      <li style={{ marginBottom: "10px" }}>
        <Link to="/servicesone" style={{ color: "#87CEFA", textDecoration: "none" }}>
          ServicesOne
        </Link>
      </li>
    </ul>
  </div>
  );
};
export default Home;